Improve Notifications
qiscus/qiscus-sdk-android pull request #10
Opened 2017-07-11 05:10 UTC by rajapulau

1. Bundled Notifications in android Nougat above
2. Heads up notifications in android Nougat above
3. Color in inline reply notifcations and you can custom it

2017-07-13 02:50 UTC, zetbaitsu commented on chat/src/main/java/com/qiscus/sdk/data/local/QiscusCacheManager.java
> +    public List<String> getRoomNotifItems() {
RoomNotifItems ini buat apa ya mas?, buat tahu berapa jumlah notif di suatu room ya?

2017-07-13 05:53 UTC, rajapulau commented on chat/src/main/java/com/qiscus/sdk/data/local/QiscusCacheManager.java
> +    public List<String> getRoomNotifItems() {
iya zet, untuk jumlah room notif. ini karena masalah remove notif di bundled aga kalau reply dari notif tidak menghapus semuanya.

2017-07-19 05:17 UTC, zetbaitsu requested changes

2017-07-19 05:17 UTC, zetbaitsu commented on chat/src/main/java/com/qiscus/sdk/data/local/QiscusCacheManager.java
> +                    .putString("push_notif_message_room_id", gson.toJson(roomNotif))
ini langsung putInt aja om, ga perlu di ubah ke json..

2017-07-19 05:17 UTC, zetbaitsu commented on chat/src/main/java/com/qiscus/sdk/data/local/QiscusCacheManager.java
> +                    .putString("push_notif_message_room_id", gson.toJson(roomNotif))
maksudnya langsung simpan dalam bentuk integer aja om, biar ga perlu di casting sama di bikin json gitu..

2017-07-19 05:18 UTC, zetbaitsu commented on chat/src/main/java/com/qiscus/sdk/data/local/QiscusCacheManager.java
> +    public List<String> getRoomNotifItems() {
yg ini nanti jadi retun List of Integer aja om..

2017-07-19 07:41 UTC, rajapulau commented on chat/src/main/java/com/qiscus/sdk/data/local/QiscusCacheManager.java
> +    public List<String> getRoomNotifItems() {
ok

2017-07-19 07:42 UTC, rajapulau commented on chat/src/main/java/com/qiscus/sdk/data/local/QiscusCacheManager.java
> +                    .putString("push_notif_message_room_id", gson.toJson(roomNotif))
ok

2017-07-24 07:32 UTC, merged