identify comment owner
qiscus/qiscus-sdk-android pull request #20
Opened 2017-10-17 09:29 UTC by adicatur

2017-10-17 09:39 UTC, zetbaitsu requested changes

2017-10-17 09:39 UTC, zetbaitsu commented on chat/src/main/java/com/qiscus/sdk/Qiscus.java
> +                    .doOnNext(qiscusAccount -> Qiscus.localDataManager.saveAccountInfo(qiscusAccount))
Ini buat apa bro?

2017-10-17 11:06 UTC, adicatur commented on chat/src/main/java/com/qiscus/sdk/Qiscus.java
> +                    .doOnNext(qiscusAccount -> Qiscus.localDataManager.saveAccountInfo(qiscusAccount))
buat nyimpen di save account info zet, soalnya kalau yg pake save itu blm ke simpen di local managernya qiscus kan y ?

nanti takutnya null di method QiscusComment.isMe() 
soalnya disitu ada Qiscus.getQiscusAccount() 

atau gimana y ?

2017-10-18 02:15 UTC, zetbaitsu commented on chat/src/main/java/com/qiscus/sdk/Qiscus.java
> +                    .doOnNext(qiscusAccount -> Qiscus.localDataManager.saveAccountInfo(qiscusAccount))
Udah ada bro

2017-10-18 02:15 UTC, zetbaitsu commented on chat/src/main/java/com/qiscus/sdk/Qiscus.java
> +                    .doOnNext(qiscusAccount -> Qiscus.localDataManager.saveAccountInfo(qiscusAccount))
Udah di simpan

2017-10-18 02:17 UTC, zetbaitsu requested changes

2017-10-18 02:17 UTC, zetbaitsu commented on chat/src/main/java/com/qiscus/sdk/data/model/QiscusComment.java
> +    public boolean isOther() {
Ga cukup satu aja bro?
isMe() itu kalo false ya other bro..
Sama nama methodnya mungkin lebih baik isMyComment()

2017-10-18 02:20 UTC, zetbaitsu commented on chat/src/main/java/com/qiscus/sdk/Qiscus.java
> +                    .doOnNext(qiscusAccount -> Qiscus.localDataManager.saveAccountInfo(qiscusAccount))
Itu kan panggil method save, di save kan udah nyimpen https://github.com/qiscus/qiscus-sdk-android/blob/master/chat/src/main/java/com/qiscus/sdk/Qiscus.java#L602

2017-10-18 03:03 UTC, adicatur commented on chat/src/main/java/com/qiscus/sdk/Qiscus.java
> +                    .doOnNext(qiscusAccount -> Qiscus.localDataManager.saveAccountInfo(qiscusAccount))
oh iya ok2

2017-10-18 03:26 UTC, merged