refactor variable type
qiscus/qiscus-sdk-android pull request #26
Opened 2017-10-23 09:27 UTC by adicatur

change variable type room id, comment id, with String

2017-10-23 13:42 UTC, zetbaitsu commented
bro @adicatur pmd nya masih fail dan codenya jg conflict bro..

2017-10-23 14:45 UTC, adicatur commented
Lupa ke push, ok zet pas pulang ak push

2017-10-24 03:39 UTC, zetbaitsu requested changes
banyak banget berubahnya, ga yakin aku ini ga ada bugnya..

2017-10-24 03:39 UTC, zetbaitsu commented on chat/src/main/java/com/qiscus/sdk/data/local/QiscusDataBaseHelper.java
>                  + QiscusDb.RoomTable.COLUMN_ID + " = " + id;
bro @adicatur yg sql query kalo string ga bisa di gini, harus di escape.. ubah jadi DatabaseUtils.sqlEscapeString(id)

2017-10-24 03:39 UTC, zetbaitsu commented on chat/src/main/java/com/qiscus/sdk/data/model/QiscusComment.java
> +                replyTo.id = payload.getString("replied_comment_id");
ini bener replied_comment_id ? bukan replied_comment_id_str ?

2017-10-24 03:39 UTC, zetbaitsu commented on chat/src/main/java/com/qiscus/sdk/data/model/QiscusReplyCommentDraft.java
> +            replyTo.setId(payload.getString("replied_comment_id"));
ini bener replied_comment_id ? bukan replied_comment_id_str ?

2017-10-24 03:39 UTC, zetbaitsu commented on chat/src/main/java/com/qiscus/sdk/data/remote/QiscusApi.java
> +                            jsonComment.get("room_id").getAsString(), jsonComment.get("topic_id").getAsString());
ini bener room_id ? bukan room_id_str ?

2017-10-24 03:39 UTC, zetbaitsu commented on chat/src/main/java/com/qiscus/sdk/data/remote/QiscusApi.java
> +                            jsonComment.get("room_id").getAsString(), jsonComment.get("topic_id").getAsString());
sama topic_id? bukan topic_id_str?

2017-10-24 03:39 UTC, zetbaitsu commented on chat/src/main/java/com/qiscus/sdk/data/remote/QiscusApiParser.java
> +            qiscusChatRoom.setId(jsonChatRoom.get("id").getAsString());
sama ini bener id? bukan id_str?

2017-10-24 03:39 UTC, zetbaitsu commented on chat/src/main/java/com/qiscus/sdk/data/remote/QiscusApiParser.java
> +            qiscusChatRoom.setLastTopicId(jsonChatRoom.get("last_topic_id").getAsString());
ini jg last_topic_id? bukan last_topic_id_str?
ya semuanya yg dari backend tur, kalo ga salah ada postfix nya str

2017-10-27 04:16 UTC, closed without merging