Update feature soundrecord
qiscus/qiscus-sdk-android pull request #3
Opened 2016-10-28 06:26 UTC by ariefnurputranto

2016-10-28 06:31 UTC, zetbaitsu commented
bro @ariefnurputranto ada conflicts, tolong dibenerin dulu ya..

2016-10-28 06:36 UTC, ariefnurputranto commented
@zetbaitsu cara mengetahui conflixnya gmn ya mas?? soalnya aku pake fork

2016-10-28 06:42 UTC, ariefnurputranto commented
udh @zetbaitsu , td dibantu mas delta sama mas ganjar buat handle dr fork

2016-10-28 13:31 UTC, zetbaitsu requested changes

2016-10-28 13:31 UTC, zetbaitsu commented on qiscus-sdk/build.gradle
> +    compile 'com.android.support:cardview-v7:24.2.0'
versinya disamaain bro dengan yg lain, 24.2.1

2016-10-28 13:31 UTC, zetbaitsu commented on qiscus-sdk/src/main/java/com/qiscus/sdk/data/model/QiscusComment.java
> +    public boolean isSound() {
pake method yg udah ada aja buat dapetin extensionnya
getExtension

2016-10-28 13:31 UTC, zetbaitsu commented on qiscus-sdk/src/main/java/com/qiscus/sdk/presenter/QiscusChatPresenter.java
> +        } else if (file.getName().endsWith(".mp3")) {
ga perlu, biarin masuk else aja kan sama2 file..
yg ".gif" dibedain karena dia gambar, tapi kalo kita compress jadi ga gerak lagi gif..

2016-10-28 13:31 UTC, zetbaitsu commented on qiscus-sdk/src/main/java/com/qiscus/sdk/ui/adapter/QiscusChatAdapter.java
> +                if(qiscusComment.getExtension().equals("mp3")){
kenapa mesti ngecek ekstensinya lagi? kan udah dihandle di qiscusComment.getType()

2016-10-28 13:31 UTC, zetbaitsu commented on qiscus-sdk/src/main/java/com/qiscus/sdk/ui/adapter/QiscusChatAdapter.java
> +                if(qiscusComment.getExtension().equals("mp3")){
sama kenapa mesti ngecek ekstensinya lagi? kan udah dihandle di qiscusComment.getType()

2016-10-28 13:31 UTC, zetbaitsu commented on qiscus-sdk/src/main/java/com/qiscus/sdk/ui/adapter/viewholder/QiscusBaseFileMessageViewHolder.java
bikin view holder baru aja buat yg tipe sound biar lebih clear

2016-10-28 13:31 UTC, zetbaitsu commented on qiscus-sdk/src/main/java/com/qiscus/sdk/ui/dialog/QiscusCustomDialog.java
> +    ImageButton buttonPlay;
access modifiernya di bikin protected aja kalo mau support inheritance, kalo ga di private aja kalo ga mau access dari luar

2016-10-28 13:31 UTC, zetbaitsu commented on qiscus-sdk/src/main/java/com/qiscus/sdk/ui/dialog/QiscusCustomDialog.java
> +    public void onCreate(@Nullable Bundle savedInstanceState) {
kalo override method terus ga di apa-apain di hapus aja, biar lebih dikit kodenya

2016-10-28 13:31 UTC, zetbaitsu commented on qiscus-sdk/src/main/java/com/qiscus/sdk/ui/dialog/QiscusCustomDialog.java
> +        buttonPlay.setOnClickListener(new View.OnClickListener() {
clicklistener gunain lambda expression biar lebih clean

2016-10-28 13:31 UTC, zetbaitsu commented on qiscus-sdk/src/main/java/com/qiscus/sdk/ui/dialog/QiscusCustomDialog.java
> +        super.onDestroyView();
override juga ga perlu

2016-10-28 13:31 UTC, zetbaitsu commented on qiscus-sdk/src/main/java/com/qiscus/sdk/ui/dialog/QiscusCustomDialog.java
> +public abstract class QiscusCustomDialog extends RxDialogFragment {
abstract class buat merepresentasikan hal2 yg umumnya ada dan dapat dilakukan oleh subclassnya, dia ga punya hal2 spesifik kayak buttonPause, seekBarSound, dsb.. itu adanya di concrete classnya aja, dalam hal ini QiscusSoundDialog

2016-10-28 13:31 UTC, zetbaitsu commented on qiscus-sdk/src/main/java/com/qiscus/sdk/ui/dialog/QiscusSoundDialog.java
> +public class QiscusSoundDialog extends QiscusCustomDialog {
yg tadi ya diatas..

2016-10-28 13:31 UTC, zetbaitsu commented on qiscus-sdk/src/main/java/com/qiscus/sdk/ui/fragment/QiscusBaseChatFragment.java
> +        if (file.getPath().contains(".mp3")) {
ini bug, kalo nama filenya akucinta.mp3.jpg
masuk sini padahal bukan sini harusnya

2016-10-28 13:31 UTC, zetbaitsu commented on qiscus-sdk/src/main/java/com/qiscus/sdk/ui/fragment/QiscusBaseChatFragment.java
> +        } else if (file.getPath().contains(".m4a")) {
sama kayak diatas

2016-10-28 13:31 UTC, zetbaitsu commented on app/src/main/java/com/qiscus/dragonfly/CustomChatAdapter.java
> +                if(qiscusComment.getExtension().equals("mp3")){
Ga perlu di lihat ekstensinya lagi

2016-10-28 13:31 UTC, zetbaitsu commented on app/src/main/res/layout/fragment_custom_chat.xml
> +                android:layout_alignParentBottom="true"
layout_alignParentX itu kalo parentnya RelativeLayout aja

2016-10-28 13:31 UTC, zetbaitsu commented on app/src/main/res/layout/fragment_custom_chat.xml
> +                                android:textColor="#4d4c4b"
kalo bisa warnanya ikutin yg udah ada di color scheme aja

2016-10-31 15:06 UTC, zetbaitsu approved these changes

2016-10-31 16:32 UTC, zetbaitsu requested changes

2016-10-31 16:32 UTC, zetbaitsu commented on app/src/main/java/com/qiscus/dragonfly/MainActivity.java
> +            Qiscus.setUser("sdk.arief@gmail.com", "arief011192")
Ini cukup perubahan di lokal mu aja rif, ga perlu masuk ke PR

2016-10-31 16:32 UTC, zetbaitsu commented on app/src/main/java/com/qiscus/dragonfly/MainActivity.java
> +        Qiscus.buildChatWith("sdk.arief2@gmail.com")
Ini juga cukup perubahan di lokal mu aja rif, ga perlu masuk ke PR

2016-10-31 16:32 UTC, zetbaitsu commented on app/src/main/res/layout/fragment_custom_chat.xml
> +                <LinearLayout
ini LinearLayout kosong buat apa ya?

2016-10-31 16:32 UTC, zetbaitsu commented on app/src/main/res/layout/fragment_custom_chat.xml
> +                        android:background="@android:color/white"
untuk warna coba pake color scheme, maksudnya ga cuma yg ini rif, tapi juga warna2 lain yg kamu pake, sama konsisten pakenya, biar nanti kalo diubah cukup sekali doang, dan semua berubah, SDK kita mesti bisa handle kustomisasi warna rif, jadi sebisa mungkin jangan di harcode juga.

2016-10-31 16:32 UTC, zetbaitsu commented on app/src/main/res/layout/fragment_custom_chat.xml
> +                        android:background="#ffffff"
ini juga masih hardcode, coba nanti kamu cari2 lagi yg kamu hardcode

2016-10-31 16:32 UTC, zetbaitsu commented on app/src/main/res/layout/fragment_custom_chat.xml
> +                                android:textSize="16dp" />
ukuran text pakenya SP rif

2016-10-31 16:32 UTC, zetbaitsu commented on app/src/main/res/layout/fragment_custom_chat.xml
> +                                android:layout_marginLeft="6dp"
kalo kamu kasih layout_marginLeft, kasih juga layout_marginStart untuk RTL (Right To Left) layout, begitupun sebaliknya kalo kamu kasih layout_marginRight, jangan lupa kasih juga layout_marginEnd, nilainya disamain aja.

2016-10-31 16:32 UTC, zetbaitsu commented on app/src/main/res/layout/fragment_custom_chat.xml
> +                            android:paddingLeft="13dp"
kalo kamu kasih paddingLeft, kasih juga paddingStart untuk support RTL (Right To Left) layout, begitupun sebaliknya kalo kamu kasih paddingRight, jangan lupa kasih juga paddingEnd, nilainya disamain aja.

2016-10-31 16:32 UTC, zetbaitsu commented on qiscus-sdk/src/main/java/com/qiscus/sdk/ui/adapter/viewholder/QiscusBaseFileMessageViewHolder.java
> +
yg ga jadi diubah di balikin aja jadi kayak semula, maskudnya satu class ini kan jadinya ga diubah, tapi bikin viewholder baru, nah class ini balikin ke posisi semula

2016-10-31 16:32 UTC, zetbaitsu commented on qiscus-sdk/src/main/java/com/qiscus/sdk/ui/adapter/viewholder/QiscusBaseSoundMessageViewHolder.java
> +            } else if (qiscusComment.getExtension().equals("m4a")) {
ini maksudnya gimana?
kalo ekstensinya m4a, terus ga ngapa-ngapain.

2016-10-31 16:32 UTC, zetbaitsu commented on qiscus-sdk/src/main/java/com/qiscus/sdk/ui/dialog/QiscusCustomDialog.java
> +    protected abstract int getResourceLayout();
buat apa kalo ga pernah dipanggil?

2016-10-31 16:32 UTC, zetbaitsu commented on qiscus-sdk/src/main/java/com/qiscus/sdk/ui/dialog/QiscusCustomDialog.java
> +    public void onDestroyView() {
override method dihapus aja kalo kalo ga ada perubahan sama sekali

2016-10-31 16:32 UTC, zetbaitsu commented on qiscus-sdk/src/main/java/com/qiscus/sdk/ui/dialog/QiscusCustomDialog.java
> +    public View view ;
cari cara yg lebih baik dari ini ya, jangan dibikin public View nya, terapin encapsulation dengan baik.

2016-10-31 16:32 UTC, zetbaitsu commented on qiscus-sdk/src/main/java/com/qiscus/sdk/ui/dialog/QiscusSoundDialog.java
> +    ImageButton buttonPlay;
encapsulation jangan lupa

2016-10-31 16:32 UTC, zetbaitsu commented on qiscus-sdk/src/main/java/com/qiscus/sdk/ui/dialog/QiscusSoundDialog.java
> +    private Context context;
hapus aja kalo ga dipake

2016-10-31 16:32 UTC, zetbaitsu commented on qiscus-sdk/src/main/java/com/qiscus/sdk/ui/dialog/QiscusSoundDialog.java
> +    public static File file;
kenapa di bikin static? itu objeknya bakal berada di memori selamanya, ga bakal kena GC.

2016-10-31 16:32 UTC, zetbaitsu commented on qiscus-sdk/src/main/java/com/qiscus/sdk/ui/dialog/QiscusSoundDialog.java
> +    private int oneTimeOnly = 0;
ini juga ga digunain

2016-10-31 16:32 UTC, zetbaitsu commented on qiscus-sdk/src/main/java/com/qiscus/sdk/ui/dialog/QiscusSoundDialog.java
> +                    seekBarSound.setOnTouchListener(new View.OnTouchListener() {
ini bisa dibikin lambda

2016-10-31 16:32 UTC, zetbaitsu commented on qiscus-sdk/src/main/java/com/qiscus/sdk/ui/dialog/QiscusSoundDialog.java
> +            mediaPlayer.setOnCompletionListener(new MediaPlayer.OnCompletionListener() {
ini bisa dibikin lambda

2016-10-31 16:32 UTC, zetbaitsu commented on qiscus-sdk/src/main/java/com/qiscus/sdk/ui/dialog/QiscusSoundDialog.java
> +            if (mediaPlayer != null) {
ini pasti true

2016-10-31 16:32 UTC, zetbaitsu commented on qiscus-sdk/src/main/java/com/qiscus/sdk/ui/fragment/QiscusBaseChatFragment.java
> +    Boolean soundTrue = false;
tolong perhatiin encapsulation

2016-10-31 16:32 UTC, zetbaitsu commented on qiscus-sdk/src/main/java/com/qiscus/sdk/ui/fragment/QiscusBaseChatFragment.java
> +    @Nullable protected LinearLayout linItemSoundRec;
mungkin bisa diganti dengan nama yg lebih deskriptif ini buat apa

2016-10-31 16:32 UTC, zetbaitsu commented on qiscus-sdk/src/main/java/com/qiscus/sdk/ui/fragment/QiscusBaseChatFragment.java
> +            showSoundDialog(file.getName(), file);
2 if ini bisa digabung pake or

2016-10-31 16:32 UTC, zetbaitsu commented on qiscus-sdk/src/main/java/com/qiscus/sdk/ui/fragment/QiscusBaseChatFragment.java
> +        // TODO Auto-generated method stub
TODO kalau itu emang todo yg harus dikerjakan dikemudian hari

2016-10-31 16:32 UTC, zetbaitsu commented on qiscus-sdk/src/main/java/com/qiscus/sdk/ui/fragment/QiscusBaseChatFragment.java
> +        chatAudioCancel.setVisibility(View.VISIBLE);
perhatiin annotationnya, @Nullable artinya bisa aja ini null, yg lain juga coba diperhatiin.

2016-10-31 16:32 UTC, zetbaitsu commented on qiscus-sdk/src/main/java/com/qiscus/sdk/util/QiscusRecordUtil.java
> +public class QiscusRecordUtil extends TimerTask {
coba cari cara yg lebih baik kalau cuma buat menghitung durasi waktu merekam suaranya.

2016-11-02 14:45 UTC, zetbaitsu commented
maaf bro @ariefnurputranto 
aku coba implementasi sendiri aja ya recordingnya https://github.com/qiscus/qiscus-sdk-android/commit/2e96d052d5ecabeaf8fa1a0d4081e7428a0b7d9e

2016-11-02 14:45 UTC, closed without merging

2016-11-03 03:07 UTC, ariefnurputranto commented
oke, maaf zet, aku blm bs mengikuti style coding mu.