adding configuration for showing or hiding image folder in gallery app
qiscus/qiscus-sdk-android pull request #30
Opened 2017-11-02 04:27 UTC by adicatur

Now user can show or hide image folder in gallery app
1. If user want to show image folder :
 `Qiscus.getChatConfig()
        .setEnableShowingImageFolderInGallery(true)`
2. if user want to hide image folder :
 `Qiscus.getChatConfig()
        .setEnableShowingImageFolderInGallery(false)`

2017-11-02 06:53 UTC, zetbaitsu requested changes

2017-11-02 06:53 UTC, zetbaitsu commented on chat/src/main/java/com/qiscus/sdk/util/QiscusImageUtil.java
> +            addImageToGallery(nomedia);
yg di rescan bukan no medianya bro, tapi semua file gambar di foldernya

2017-11-02 06:53 UTC, zetbaitsu commented on chat/src/main/java/com/qiscus/sdk/util/QiscusImageUtil.java
> +        if (!nomedia.exists()) {
tambahin nomedia.mkdirs(); bro buat handle kalau foldernya belum ada

2017-11-02 06:53 UTC, zetbaitsu commented on chat/src/main/java/com/qiscus/sdk/data/model/QiscusChatConfig.java
> +    private boolean enableShowingImageFolderInGallery = true;
ini kan ga digunakan lagi?

2017-11-02 06:54 UTC, zetbaitsu commented on chat/src/main/java/com/qiscus/sdk/util/QiscusImageUtil.java
> +            addImageToGallery(nomedia);
nomedianya udah ga ada, udah di delete

2017-11-02 07:33 UTC, adicatur commented on chat/src/main/java/com/qiscus/sdk/util/QiscusImageUtil.java
> +            addImageToGallery(nomedia);
iya udah di delet tapi yang gallery perlu di notif zet, 
addImageToGallery(nomedia); 
^ ini bisa sih, ak mikirnya dari pada looping semua file mending yg pake nomedia nya , menurutmu gimana ?

2017-11-02 07:34 UTC, zetbaitsu commented on chat/src/main/java/com/qiscus/sdk/util/QiscusImageUtil.java
> +            addImageToGallery(nomedia);
tapi bisa jalan bro?

2017-11-02 07:35 UTC, zetbaitsu commented on chat/src/main/java/com/qiscus/sdk/util/QiscusImageUtil.java
> +            addImageToGallery(nomedia);
maksudnya foldernya jadi keliatan lagi di gallery?

2017-11-02 07:35 UTC, zetbaitsu commented on chat/src/main/java/com/qiscus/sdk/util/QiscusImageUtil.java
> +            addImageToGallery(nomedia);
kalo bisa keliatan lagi, ya mending gitu aja..

2017-11-02 07:37 UTC, adicatur commented on chat/src/main/java/com/qiscus/sdk/util/QiscusImageUtil.java
> +        if (!nomedia.exists()) {
malah nanti hasilnya bukannya folder ".nomedia" y, padahal kan harusnya file aja kan zet ?

2017-11-02 07:39 UTC, adicatur commented on chat/src/main/java/com/qiscus/sdk/util/QiscusImageUtil.java
> +            addImageToGallery(nomedia);
iya bisa cuy wkwk

2017-11-02 07:40 UTC, adicatur commented on chat/src/main/java/com/qiscus/sdk/data/model/QiscusChatConfig.java
> +    private boolean enableShowingImageFolderInGallery = true;
hoo ak hapus yk

2017-11-02 07:40 UTC, zetbaitsu commented on chat/src/main/java/com/qiscus/sdk/util/QiscusImageUtil.java
> +        if (!nomedia.exists()) {
berarti parentnya aja bro..
```java
if (nomedia.getParentFile().exists()) {
    nomedia.mkdirs();
}
```

2017-11-02 07:44 UTC, adicatur commented on chat/src/main/java/com/qiscus/sdk/util/QiscusImageUtil.java
> +        if (!nomedia.exists()) {
ok ak testing yak

2017-11-02 08:11 UTC, adicatur commented on chat/src/main/java/com/qiscus/sdk/util/QiscusImageUtil.java
> +        if (!nomedia.exists()) {
updated ya

2017-11-02 08:13 UTC, zetbaitsu commented on chat/src/main/java/com/qiscus/sdk/data/model/QiscusChatConfig.java
> +    private boolean enableShowingImageFolderInGallery = true;
yg ini belum di hapus bro?

2017-11-03 02:47 UTC, zetbaitsu approved these changes

2017-11-03 02:48 UTC, merged