add feature quick reply from notification
qiscus/qiscus-sdk-android pull request #9
Opened 2017-05-27 06:11 UTC by rajapulau

1. Default dari feature ini ada `false`. untuk menggunakannya melalui qiscus config 
`Qiscus.getChatConfig().setEnableReplyNotification(true)`
2. Reply ini support untuk Android N, sedangkan versi dibawah Android N akan muncul dialog untuk membalaskan chat. saat ini dialog hanya menampilkan nama, avatar dan input text. 
3. Dialog reply belum dapat di override dari config. next akan dapat configable untuk style dialog ini. dan next akan juga diusahakan dapat membalas pesan audio maupun image. dan beberapa feature lainnya

2017-05-30 06:42 UTC, zetbaitsu commented
nice mas...
gimana kalau kita pakai QiscusChatFragment lagi aja mas untuk dialognya, jadi bisa include semua fitur yg sudah ada di chatroom, kalau sekarangkan baru bisa kirim pesan text doang, sama baru bisa render text message juga kan.. tapi kalau pakai fragment itu lagi, kita bisa support semuanya mas 😬

2017-05-30 06:44 UTC, zetbaitsu commented
misalnya kayak gini mas, ini contoh pakai bawaan samsung bisa bikin apps jadi melayang..
![screenshot_20170530-133937](https://cloud.githubusercontent.com/assets/10556814/26571068/1c10b7c8-453e-11e7-9a0e-072f37571749.png)

2017-05-30 06:52 UTC, rajapulau commented
wo, itu cuma featurenya samsung kan ya ? btw yang dimaksud `QiscusChatFragment` itu untuk dialognya ?

2017-05-30 06:59 UTC, zetbaitsu commented
iya mas itu fitur samsung, ga tau hp lain..
dialog mas, tapi isinya QiscusChatFragment.. jadi yg ini https://github.com/qiscus/qiscus-sdk-android/pull/9/files#diff-9e48c38460ecdbd8f43c7409130943d4 jadi containernya QiscusChatFragment aja mas, kayak QiscusChatActivity itu mas kan layoutnya cuma toolbar sama fragment container https://github.com/qiscus/qiscus-sdk-android/blob/master/chat/src/main/res/layout/activity_qiscus_chat.xml#L93

2017-05-30 07:00 UTC, zetbaitsu commented on chat/src/main/java/com/qiscus/sdk/util/QiscusReplyDialog.java
> +package com.qiscus.sdk.util;
ini di package com.qiscus.sdk.ui.dialog aja mas

2017-05-30 07:08 UTC, rajapulau commented on chat/src/main/java/com/qiscus/sdk/util/QiscusReplyDialog.java
> +package com.qiscus.sdk.util;
ok

2017-05-31 03:30 UTC, zetbaitsu requested changes

2017-05-31 03:30 UTC, zetbaitsu commented on chat/src/main/java/com/qiscus/sdk/data/model/QiscusChatConfig.java
> +    public QiscusChatConfig setEnableReplyNotification(boolean enableReplyNotification) {
kasih anotasi ini mas @RequiresApi(api = Build.VERSION_CODES.N)

2017-05-31 03:30 UTC, zetbaitsu commented on chat/src/main/java/com/qiscus/sdk/data/model/QiscusChatConfig.java
> +    public ReplyNotificationHandler sendReplyNotificationHandler() {
nama methodnya ganti getReplyNotificationHandler() aja mas, terus tambahin setternya mas

2017-05-31 03:30 UTC, zetbaitsu commented on chat/src/main/java/com/qiscus/sdk/service/QiscusPusherService.java
> +        if (Qiscus.getChatConfig().isEnableReplyNotification()) {
dan Build.VERSION.SDK_INT >= Build.VERSION_CODES.N

2017-05-31 03:30 UTC, zetbaitsu commented on chat/src/main/res/drawable/qiscus_rounded_primary_top.xml
> +<shape xmlns:android="http://schemas.android.com/apk/res/android">
di hapus aja ya mas

2017-05-31 03:30 UTC, zetbaitsu commented on chat/src/main/res/layout/fragment_qiscus_reply_dialog.xml
> +<?xml version="1.0" encoding="utf-8"?>
ini juga ga digunain lagi kan ya, dihapus aja mas

2017-05-31 04:34 UTC, zetbaitsu approved these changes

2017-05-31 04:35 UTC, merged